// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    ComponentSettings: typeof import('./components/ComponentSettings.vue')['default']
    Documentation: typeof import('./components/documentation/Documentation.vue')['default']
    GroupedHits: typeof import('./components/GroupedHits.vue')['default']
    'Ic:roundCancel': typeof import('~icons/ic/round-cancel')['default']
    'Ic:roundSearch': typeof import('~icons/ic/round-search')['default']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SearchHit: typeof import('./components/SearchHit.vue')['default']
    SearchInterface: typeof import('./components/documentation/SearchInterface.vue')['default']
    SearchProperty: typeof import('./components/documentation/SearchProperty.vue')['default']
    'SearchProperty copy': typeof import('./components/SearchProperty copy.vue')['default']
    SearchResults: typeof import('./components/SearchResults.vue')['default']
    SearchSlot: typeof import('./components/documentation/SearchSlot.vue')['default']
    Separator: typeof import('./components/Separator.vue')['default']
  }
}

export { }
